### ISSUE TITLE
SOS Emergency Feature Implementation

### ISSUE THREAD

**Issue by dhrumilp12** [dhrumilp12/Health-Sync#6]
Objective: Develop the SOS emergency feature with location sharing and emergency contacts notification.
Tasks:

- [x] Implement one-click emergency call functionality.
- [x] Integrate GPS location sharing.
- [x] Set up automatic notifications to predefined emergency contacts.
- [x] Develop a system to store and instantly share critical medical information with emergency responders.

**Comment by ghoshvidip26** [comment]
I would like to work on this feature.

**Comment by dhrumilp12** [comment]
Used: 

1. Twilio- for one click emergency call.
2. Geocoder for GPS location sharing.
